=== Redchush/XMLProject/root/source/xml/Menu_XSD.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"

            elementFormDefault="qualified"
            attributeFormDefault="unqualified"
            version="1.0">
    <!-- in this schema was implemented Venetian Blind pattern -->
    <xsd:complexType name="MenuType">
        <xsd:sequence>

            <xsd:element name="category" type="CategoryType" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="name"/>
        <xsd:attribute name="version"/>
    </xsd:complexType>

   <!-- category of menu description -->

    <xsd:complexType name="CategoryType">
        <xsd:sequence>
            <xsd:element name="title" type="CategoryTitleType"/>
            <xsd:choice maxOccurs="unbounded">
                <xsd:element name="simpleMenuItem">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="menuItem" type="SimpleMenuItemType"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>

                <xsd:element name="complexMenuItem">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="menuItem" type="ComplexMenuItemType"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>

            </xsd:choice>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:simpleType name="CategoryTitleType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="ХОЛОДНЫЕ ЗАКУСКИ"/>
            <xsd:enumeration value="ГОРЯЧИЕ ЗАКУСКИ"/>
            <xsd:enumeration value="ЗАВТРАКИ"/>
            <xsd:enumeration value="ДЕСЕРТЫ"/>
        </xsd:restriction>
    </xsd:simpleType>


    <!-- there are 2 based types of menu item: simple consist of only one dish variant,
        complex include two or more dish variants -->

    <xsd:complexType name="SimpleMenuItemType">
        <xsd:sequence>
            <xsd:group ref="unchangableMenuItemComponents"/>
            <xsd:element name="description" minOccurs="0"/>
            <xsd:element name="ratio" type="ratioType"/>
            <xsd:element name="price" minOccurs="0" type="SimplePriceType"/>
        </xsd:sequence>
        <xsd:attribute name="isComplex" type = "xsd:boolean" fixed="false"/>
        <xsd:attribute name="id" type="xsd:ID" use="required" />
    </xsd:complexType>

    <xsd:complexType name="ComplexMenuItemType">
        <xsd:sequence>
            <xsd:group ref="unchangableMenuItemComponents"/>
            <xsd:element name="description" type="ComplexDescriptionType"/>
            <xsd:element name="ratio" type="ratioType"/>
            <xsd:element name="price" type="ComplexPriceType"/>
        </xsd:sequence>
        <xsd:attribute name="isComplex" type = "xsd:boolean" fixed="true"/>
        <xsd:attribute name="id" type="xsd:ID" use="required" />
    </xsd:complexType>

    <!-- description of types -->

    <!--this property is same for both types -->
    <xsd:group name="unchangableMenuItemComponents">
        <xsd:sequence>
            <xsd:element name="foto">
                <xsd:complexType>
                    <xsd:attribute name="path"/>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="name"/>
        </xsd:sequence>

    </xsd:group>


    <xsd:complexType name="ratioType">
        <xsd:simpleContent>
            <xsd:extension base="RatioListType">
                <xsd:attribute name="separator" use="optional" default="/"/>
                <xsd:attribute name="unit" use="optional" default="грамм"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

    <xsd:simpleType name="RatioListType">
        <xsd:list itemType="xsd:integer"> </xsd:list>
    </xsd:simpleType>

    <!-- property for simple type -->

    <xsd:simpleType name="SimplePriceType">
        <xsd:restriction base="xsd:decimal">
            <xsd:minExclusive value="0.0"/>
            <xsd:fractionDigits value="2"/>
        </xsd:restriction>
    </xsd:simpleType>

    <!-- property for complex type-->

    <xsd:complexType name="ComplexPriceType">
        <xsd:sequence>
            <xsd:element name="priceForExactType" maxOccurs="unbounded">
                <xsd:complexType>
                    <xsd:simpleContent>
                        <xsd:extension base="xsd:string">
                            <xsd:attribute name="variantNumber" type="xsd:byte"/>
                        </xsd:extension>
                    </xsd:simpleContent>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="ComplexDescriptionType">
        <xsd:sequence>
            <xsd:element name="menuItemVariant" maxOccurs="unbounded">
                <xsd:complexType>
                    <xsd:simpleContent>
                        <xsd:extension base="xsd:string">
                            <xsd:attribute name="variantNumber"/>
                        </xsd:extension>
                    </xsd:simpleContent>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>


    <xsd:element name="menu" type="MenuType"/>

  </xsd:schema>

=== Redchush/XMLProject/root_task_2_1/source/xml/Menu_XML.xml
<?xml version="1.0" encoding="UTF-8"?>
<menu name = "Меню" version="4"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="Menu_XSD.xsd">

    <category>
        <title>ХОЛОДНЫЕ ЗАКУСКИ</title>
        <simpleMenuItem>
            <menuItem id="C_1">
                <foto path="../images/fish.jpeg"/>
                <name>Ассорти рыбное</name>
                <description>Слабосоленая форель,семга</description>
                <ratio unit="грамм">100 20 15</ratio>
            </menuItem>
        </simpleMenuItem>

        <simpleMenuItem>
            <menuItem id="C_2">
                <foto path="undefined"/>
                <name>Тарталетки с красной игрой</name>
                <description>Тарталетки с красной игрой</description>
                <ratio unit="грамм">60 50</ratio>
            </menuItem>
        </simpleMenuItem>

        <simpleMenuItem>
            <menuItem id="C_3" >
                <foto path="undefined"/>
                <name>Лимон</name>
                <description></description>
                <ratio unit="грамм">60</ratio>
            </menuItem>
        </simpleMenuItem>
    </category>

    <category>
        <title>ГОРЯЧИЕ ЗАКУСКИ</title>

        <simpleMenuItem>
            <menuItem id="H_1">
                <foto path="undefined"/>
                <name>Лобио с шампиньонами</name>
                <description></description>
                <ratio unit="грамм">60 5</ratio>
            </menuItem>
        </simpleMenuItem>

        <complexMenuItem>
            <menuItem isComplex="true"  id="H_2" >
                <foto path="undefined"></foto>
                <name>Жульен</name>
                <description>
                    <menuItemVariant variantNumber="1">c курицей</menuItemVariant>
                    <menuItemVariant variantNumber="2">c грибами</menuItemVariant>
                </description>
                <ratio unit="грамм">120 1</ratio>
                <price>
                    <priceForExactType variantNumber="1">145</priceForExactType>
                    <priceForExactType variantNumber="2">155</priceForExactType>
                </price>
            </menuItem>
        </complexMenuItem>

        <simpleMenuItem>
            <menuItem id="H_3" >
                <foto path="undefined"></foto>
                <name>Ахтамар мясной</name>
                <description> Колбаса, ветчина, буженина, сыр, запеченые на мангале</description>
                <ratio unit="шт">1</ratio>
                <price>165</price>
            </menuItem>
        </simpleMenuItem>

    </category>

    <category>
        <title>ЗАВТРАКИ</title>
        <simpleMenuItem>
            <menuItem id="B_1" >
                <foto path="undefined"></foto>
                <name>Глазунья</name>
                <description> 2 яйца </description>
                <ratio unit="грамм">150</ratio>
                <price>165</price>
            </menuItem>
        </simpleMenuItem>

        <simpleMenuItem>
            <menuItem id="B_2">
                <foto path="undefined"></foto>
                <name>Омлет</name>
                <description></description>
                <ratio unit="грамм">100</ratio>
                <price>165</price>
            </menuItem>
        </simpleMenuItem>

        <simpleMenuItem>
            <menuItem id="B_3">
                <foto path="undefined"></foto>
                <name>Блинчики с мясом</name>
                <description>Жареные блинчики с мясом</description>
                <ratio unit="грамм">150</ratio>
                <price>165</price>
            </menuItem>
        </simpleMenuItem>

    </category>
</menu>
